# Generated by Django 5.2.1 on 2025-05-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("student_id", models.IntegerField(blank=True, null=True)),
                (
                    "event_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("event_name", models.CharField(blank=True, max_length=100, null=True)),
                ("claim", models.CharField(blank=True, max_length=2000, null=True)),
                ("claim_url", models.CharField(blank=True, max_length=200, null=True)),
                ("post_url", models.CharField(blank=True, max_length=20, null=True)),
                ("label", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name_plural": "Events",
                "db_table": "events",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                ("event_id", models.CharField(blank=True, max_length=20, null=True)),
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_url", models.CharField(blank=True, max_length=200, null=True)),
                ("platform", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "student_label",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "img_vid_none",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("likes", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "post_timestamp",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("comments", models.CharField(blank=True, max_length=200, null=True)),
                ("views", models.CharField(blank=True, max_length=20, null=True)),
                ("shares", models.CharField(blank=True, max_length=20, null=True)),
                ("reposts", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "annotator1",
                    models.CharField(
                        blank=True,
                        choices=[("0", "Real"), ("1", "Fake")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "annotator2",
                    models.CharField(
                        blank=True,
                        choices=[("0", "Real"), ("1", "Fake")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "annotator3",
                    models.CharField(
                        blank=True,
                        choices=[("0", "Real"), ("1", "Fake")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts",
                "db_table": "posts",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PostsComments",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_id", models.IntegerField(blank=True, null=True)),
                ("text", models.CharField(blank=True, max_length=2000, null=True)),
                ("user", models.CharField(blank=True, max_length=20, null=True)),
                ("likes", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "student_label",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "annotator1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Agree", "Agree"),
                            ("Disagree", "Disagree"),
                            ("Query", "Query"),
                            ("Comment", "Comment"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "annotator2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Agree", "Agree"),
                            ("Disagree", "Disagree"),
                            ("Query", "Query"),
                            ("Comment", "Comment"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "annotator3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Agree", "Agree"),
                            ("Disagree", "Disagree"),
                            ("Query", "Query"),
                            ("Comment", "Comment"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Post Comments",
                "db_table": "posts_comments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PostsUsers",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                ("followers", models.CharField(blank=True, max_length=20, null=True)),
                ("followings", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "verified_unverfied",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("dp_url", models.CharField(blank=True, max_length=200, null=True)),
                ("posts_count", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "joining_date",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Posts Users",
                "db_table": "posts_users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name_plural": "Students",
                "db_table": "students",
                "managed": True,
            },
        ),
    ]
