# Generated by Django 5.2.1 on 2025-05-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'managed': False, 'verbose_name_plural': 'Events'},
        ),
    ]
